Name=(input("ENTER THE NAME: "))
PYTHON_MARKS=int(input("ENTER THE PYTHON MARKS:"))
SQL_MARKS=int(input("ENTER THE SQL MARKS:"))
MATHS_MARKS=int(input("ENTER THE MATHS MARKS "))

TOTAL=(PYTHON_MARKS+SQL_MARKS+MATHS_MARKS)
AVERAGE=TOTAL/3

print("THE TOTAL NUMBER OBTAINED IS: ",TOTAL)
print("THE AVERAGE SCORE IS :", AVERAGE)
